[Round1] 자바스크립트 공부
GDSC-Hongik/2023-2-Project-Track-FE pull request #6
Opened 2023-11-13 13:03 UTC by YeonUk-Kim0120

## 📌 학습 진행 상황  
코드잇 사이트에서 프로그래밍 핵심 개념 in JavaScript, 프로그래밍과 데이터 in JavaScript, 인터랙티브 자바스크립트 강의를 다 수강하였다. 
## 🔗 WIL  

https://velog.io/@ukyeon/프로그래밍-핵심-개념-in-JavaScript
https://velog.io/@ukyeon/인터랙티브-자바스크립트
https://velog.io/@ukyeon/프로그래밍과-데이터-in-JavaScript

## 🫠 어려웠던 점, 보완해야 할 점   

처음 강의를 들었을 때는 잘 느끼지 못했지만, 점점 강의를 들어갈 수록 css와 html에 대한 지식이 너무 부족하다는 것을 느꼈다. 실습할때 js뿐만 아니라 html코드와 css코드를 둘 다 볼 줄 알고 있어야 실습을 해결할 수 있다는 것을 느꼈다. 지금부터 이러면 나중에 가면 더 힘들어질 것 같다라는 생각이 들어서 html과 css도 같이 공부를 해야겠다고 생각이 들었다. 그리고 js가 다른 프로그래밍 언어와 문법은 많이 겹치지만 작동방식이 좀 다르다는 것을 느껴서 이것에 익숙해져야 함을 느꼈다.  이제부터는 진짜 생각보다 많이 어려울 것 같다. 안되면 두번씩이라도 들어봐야겠다.

## 📚 앞으로의 계획   

다음주까지 앞 부분 강의를 다시 한 번 듣고 다음주부터는 하루에 1장,2장,3장 이렇게 한 번에 많이 듣지 않고, 하루에 최대 1장만 들으면서 적지만 좀 더 깊게 공부를 해봐야할 것 같다. 그리고 2일에 한 번씩 많이 하는 것보다 매일매일 조금씩 하는게 좀 더 기억에 많이 남는 것 같다라는 생각이 들어서 조금이라도 매일매일 뺴먹지 않고 해보는 습관을 들일 예정입니다.  css코드와 html 코드도 유심히 보면서 진행해야할 것 같습니다. 더 열심히 해보자~~

2023-11-13 15:13 UTC, eugene028 approved these changes
https://github.com/GDSC-Hongik/2023-2-Project-Track-FE/pull/3/files
여기 링크에 있는 것 참고해서 다음 과제 제출 때는 제출 형식을 바꿔봅시다!
1. `.github` 폴더 내에서 `YeonUk-Kim0120` 폴더 꺼내놓기 (루트 폴더로 명시)
2. javascript 파일은 `.js` 파일로 작성, WIL과 같은 글로 정리하는 것은 `md`로 작성하기!
그리고 1,2번 팁 전달합니다

2023-11-14 09:12 UTC, YeonUk-Kim0120 commented
넵! 다음과제에서 형식 바꿔서 제출하겠습니다!! 감사합니당

2023년 11월 14일 (화) 오전 12:13, Eugene Kim ***@***.***>님이 작성:

> ***@***.**** approved this pull request.
>
> https://github.com/GDSC-Hongik/2023-2-Project-Track-FE/pull/3/files
> 여기 링크에 있는 것 참고해서 다음 과제 제출 때는 제출 형식을 바꿔봅시다!
>
>    1. .github 폴더 내에서 YeonUk-Kim0120 폴더 꺼내놓기 (루트 폴더로 명시)
>    2. javascript 파일은 .js 파일로 작성, WIL과 같은 글로 정리하는 것은 md로 작성하기!
>    그리고 1,2번 팁 전달합니다
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GDSC-Hongik/2023-2-Project-Track-FE/pull/6#pullrequestreview-1727539484>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASIA7RQSHOGQZZBLRZFTYOTYEI2J7AVCNFSM6AAAAAA7JDZ3MKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMRXGUZTSNBYGQ>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-11-14 21:10 UTC, eugene028 requested changes
넹 일단은 이거 머지해야 하니 폴더구조만 바꿔서 다시 커밋해주세요!

2023-11-15 02:26 UTC, YeonUk-Kim0120 commented
넵 방금 다시 커밋했습니다!

2023년 11월 15일 (수) 오전 6:10, Eugene Kim ***@***.***>님이 작성:

> ***@***.**** requested changes on this pull request.
>
> 넹 일단은 이거 머지해야 하니 폴더구조만 바꿔서 다시 커밋해주세요!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GDSC-Hongik/2023-2-Project-Track-FE/pull/6#pullrequestreview-1730809854>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASIA7RVTQFHHVB57DCACFSLYEPM5XAVCNFSM6AAAAAA7JDZ3MKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMZQHAYDSOBVGQ>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-11-18 06:47 UTC, eugene028 approved these changes
수고하셨습니다!

2023-11-18 06:47 UTC, merged